---
version: '3.3'
   
services:
  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=aws-access-key-id
      - AWS_SECRET_ACCESS_KEY=aws-secret-access-key
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_DYNAMODB_LOCAL_ADDRESS=http://db:8000
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 3001:3000
    environment:
      - MYWEATHER_API_URL=http://backend:8080
    depends_on:
      - backend
